[build]
  # This command forces the build image to download and use the .NET 9 SDK
  command = "mise use -g dotnet@10 && dotnet publish -c Release -o release"
  publish = "release/wwwroot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
